import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        alignItems: 'stretch',
        justifyContent: 'flex-end',
    },
    
    landingBG: {
        height: '100%',
        width: '100%',
    },

    btnContainer: {
        flexDirection: 'row',
        paddingTop: '56%',
        justifyContent: 'center',
    },

    startBtn: {
        backgroundColor: '#ffff',
        width: '25%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        margin: 5,
    },
    
    btnText: {
        fontSize: 15,
        fontFamily: 'Quicksand-Medium',
        fontWeight: 'bold',
        color: '#2e2d27',
    },

    P1text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        top: 20,
        textAlign: 'justify',
    },

    nextBtn1: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '112%',
    },

    P2text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        top: '65%',
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn2: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '105%',
    },

    nextBtn2E: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '112%',
    },

    P3text: {
        fontSize: 15,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn3: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    nextBtn3E: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '97%',
    },

    P4text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn4: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    nextBtn4E: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '83%',
    },

    P5text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn5: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '98%',
    },

    nextBtn5E: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '98%',
    },

    P6text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn6: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '98%',
    },

    P7text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'5%',
    },

    P7Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn7: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '112%',
    },

    nextBtn7M: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '105%',
    },

    P8text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'5%',
    },

    nextBtn8: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '97%',
    },

    P8Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn8M: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    P9text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn9: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '77%',
    },

    nextBtn9M: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    P10text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'5%',
    },

    nextBtn10: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '113%',
    },

    P10Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn10M: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '97%',
    },

    P11text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 27,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn11: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '113%',
    },

    P12text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 27,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn12: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '107%',
    },

    P12Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 18,
        lineHeight: 26,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn12M: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '95%',
    },

    P13text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 27,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'6%',
    },

    nextBtn13: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '120%',
    },

    nextBtn13M: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '113%',
    },

    P14text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn14: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '107%',
    },

    P14Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Medium',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'7%',
    },

    nextBtn14M: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '111%',
    },

    HomeBtn: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '28%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 147,
        top: '114%',
    },

    QuizBtn: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 168,
        top: '85%',
    },
});

export default styles;