import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        alignItems: 'stretch',
        justifyContent: 'flex-end',
    },
    
    landingBG: {
        height: '100%',
        width: '100%',
    },

    btnContainer: {
        flexDirection: 'row',
        paddingTop: '56%',
        justifyContent: 'center',
    },

    startBtn: {
        backgroundColor: '#ffff',
        width: '25%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        margin: 5,
    },
    
    btnText: {
        fontSize: 15,
        fontFamily: 'Quicksand-Medium',
        fontWeight: 'bold',
        color: '#2e2d27',
    },
    AudioText: {
            fontSize: 14,
            fontFamily: 'Quicksand',
            color: '#2e2d27',
            fontStyle: 'italic',
            textDecorationLine: 'underline',
    },

    P1text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        top: 20,
        textAlign: 'justify',
    },
    
    AudioBtnP1E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: 10,
    },

    nextBtn1: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '105%',
    },

    P2text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        top: '62%',
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    AudioBtnP2E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: '99%',
    },

    nextBtn2: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '97%',
    },

    nextBtn2E: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '98%',
    },

    P3text: {
        fontSize: 15,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    P3textM: {
        fontSize: 13,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    AudioBtnP3E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: -40,
    },

    AudioBtnP3M:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: 0,
    },

    nextBtn3: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '83%',
    },

    nextBtn3E: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '83%',
    },

    P4text: {
        fontSize: 14,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    AudioBtnP4E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: -12,
    },

    nextBtn4: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '83%',
    },

    nextBtn4E: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '83%',
    },

    P5text: {
        fontSize: 15,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    AudioBtnP5E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: -10,
    },

    nextBtn5: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    nextBtn5E: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    P6text: {
        fontSize: 14,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    AudioBtnP6E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: -12,
    },

    nextBtn6: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    P7text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    AudioBtnP7E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: 7,
    },

    P7Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn7: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '105%',
    },

    nextBtn7M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '97%',
    },

    P8text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'5%',
    },

    AudioBtnP8E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 15,
        top: 25,
    },

    nextBtn8: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '90%',
    },

    P8Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn8M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '82%',
    },

    P9text: {
        fontSize: 14,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    AudioBtnP9E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: -17,
    },

    nextBtn9: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '75%',
    },

    nextBtn9M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '82%',
    },

    P10text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    AudioBtnP10E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: -18,
    },

    AudioBtnP10M:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: -40,
    },

    nextBtn10: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '97%',
    },

    P10Mtext: {
        fontSize: 15,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn10M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '83%',
    },

    P11text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 27,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'2%',
    },

    AudioBtnP11E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: 7,
    },

    AudioBtnP11M:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: -20,
    },

    nextBtn11: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '106%',
    },

    nextBtn11M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '100%',
    },

    P12text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 27,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    AudioBtnP12E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: 10,
    },

    AudioBtnP12M:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: -5,
    },

    nextBtn12: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '100%',
    },

    P12Mtext: {
        fontSize: 14,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 18,
        lineHeight: 26,
        justifyContent: 'space-between',
        textAlign: 'justify',
    },

    nextBtn12M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '89%',
    },

    P13text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 27,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'4%',
    },

    AudioBtnP13E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: 17,
    },

    nextBtn13: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '107%',
    },

    nextBtn13M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '106%',
    },

    P14text: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    AudioBtnP14E:{
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '15%',
        height: 30,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
        flexDirection: 'row',
        left: 10,
        top: 25,
    },

    nextBtn14: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '100%',
    },

    P14Mtext: {
        fontSize: 16,
        fontFamily: 'Quicksand-Bold',
        color: '#2e2d27',
        padding: 20,
        lineHeight: 30,
        justifyContent: 'space-between',
        textAlign: 'justify',
        top:'3%',
    },

    nextBtn14M: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 310,
        top: '103%',
    },

    HomeBtn: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '28%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 147,
        top: '114%',
    },

    QuizBtn: {
        backgroundColor: '#fff',
        opacity: '100%',
        width: '18%',
        height: 50,
        borderRadius: 20,
        textAlign: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        flexDirection: 'row',
        left: 168,
        top: '85%',
    },

});

export default styles;